title: 0x0h3mz4
email: habshadyy@gmail.com
description: CyberSec blogs,ctfs,writeups...
author: 0x0h3mz4
baseurl: ""
url: "https://0x0h3mz4.github.io"

# Social Profiles
twitter_username: 0x0h3mz4
github_username: 0x0h3mz4
facebook_username:
instagram_username:
linkedin_username: Hamza AIT BAMOH

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
future: true
